name = "imgcaption-com"          # Worker 名字，最好全小写无空格
main = "./src/index.js"                # 入口文件
account_id = "26efe7e8e4f6523e0ec64661415e776b"
compatibility_date = "2025-07-22"

workers_dev = true               # 开发子域 *.workers.dev 先试跑
routes = ["https://api.imgcaption.com/*" ]  # 绑定自定义域



# 环境变量不要写死在文件里！
[vars]
# 这里放公开不敏感变量；私钥类用 wrangler secret