# This is the configuration file for your Cloudflare Worker.

# The name of your Worker. This will be part of its URL.
# Replace "ai-caption-proxy" with the name you chose in the Cloudflare dashboard.
name = "imgcaption-com.shaoneng-wu.workers.dev"

# The entry point for your Worker script.
# This tells Wrangler that your main code is in the "src/index.js" file.
main = "src/index.js"

# Specifies the runtime compatibility date.
# Using a recent date ensures you have access to the latest Worker features.
compatibility_date = "2024-03-20"
